Repository puppetlabs/puppetlabs-puppet_metrics_collector, pull requests merged in 2021-06, with the labels that each got.

#100 Added in change log and litmus gems
  .ruby-version
  .sync.yml
  Gemfile
Labels: maintenance

#103 Add PuppetDB Jetty thread metrics
  manifests/service/puppetdb.pp
Labels: feature

#102 Expose additional_metrics for each service
  manifests/service/ace.pp
  manifests/service/activemq.pp
  manifests/service/bolt.pp
  manifests/service/orchestrator.pp
  manifests/service/puppetdb.pp
  manifests/service/puppetserver.pp
Labels: feature

#109 add idempotency acceptance testing
  .fixtures.yml
  .github/workflows/pe_latest_testing.yml
  .github/workflows/pe_lts_testing.yml
  .rubocop.yml
  .sync.yml
  spec/acceptance/init_spec.rb
  spec/spec_helper.rb
  spec/spec_helper_acceptance.rb
  spec/spec_helper_acceptance_local.rb
Labels: maintenance

#111 Remove collection of AMQ metrics
  files/amq_metrics
  manifests/init.pp
  manifests/service/activemq.pp
Labels: backwards-incompatible

#99 SUP-2192 Migration from Cron, to SystemD timers for Database Maintenance
  .sync.yml
  files/metrics_tidy
  files/psql_metrics
  lib/facter/puppet_metrics_collector.rb
  manifests/collect.pp
  manifests/init.pp
  manifests/pe_metric.pp
  manifests/sar_metric.pp
  manifests/service/ace.pp
  manifests/service/bolt.pp
  manifests/service/orchestrator.pp
  manifests/service/puppetdb.pp
  manifests/service/puppetserver.pp
  manifests/system.pp
  manifests/system/cpu.pp
  manifests/system/memory.pp
  manifests/system/postgres.pp
  manifests/system/processes.pp
  manifests/system/vmware.pp
  spec/acceptance/init_spec.rb
  spec/classes/init_spec.rb
  spec/classes/puppet_metrics_collector_system_spec.rb
  spec/default_facts.yml
  spec/defines/pe_metric_spec.rb
  spec/spec_helper_acceptance_local.rb
  templates/service.epp
  templates/tidy.epp
  templates/tidy_timer.epp
  templates/timer.epp
Labels: backwards-incompatible

#112 Add PuppetDB message queue metrics
  manifests/service/puppetdb.pp
Labels: feature

#96 (GH-95) Use -I with pidstat with system_processes
  files/system_metrics
Labels: bugfix

#115 Add pe_metric acceptance test and improve init spec test
  spec/acceptance/functions/hosts_with_pe_profile_spec.rb
  spec/acceptance/init_spec.rb
  spec/acceptance/pe_metric_spec.rb
Labels: maintenance

#117 (maint) Add acceptance tests for the services
  spec/acceptance/functions/hosts_with_pe_profile_spec.rb
  spec/acceptance/init_spec.rb
  spec/acceptance/pe_metric_spec.rb
Labels: maintenance

#119 PE Version and PDK Update
  .github/workflows/pe_latest_testing.yml
  .github/workflows/pe_lts_testing.yml
  .gitignore
  .pdkignore
  metadata.json
  spec/spec_helper.rb
Labels: maintenance

#120 (SUP-2493) Remove Puppet 5.x support
  metadata.json
Labels: backwards-incompatible

#121 (SUP-2493) Remove support for SysVinit operating systems
  metadata.json
Labels: backwards-incompatible

#123 (maint) Remove Oracle 8 and Scientific 8
  metadata.json
Labels: maintenance

#116 (GH-108) Disable sysstat management by default
  lib/facter/puppet_metrics_collector.rb
  manifests/system.pp
  spec/acceptance/pe_metric_spec.rb
  spec/acceptance/pe_system_spec.rb
  spec/classes/puppet_metrics_collector_system_spec.rb
Labels: backwards-incompatible, feature
