Repository puppetlabs/puppetlabs-puppet_metrics_collector, pull requests merged in 2021-07, with the labels that each got.

#94 (SUP-1969) Enable metrics shipping for all system types
  files/psql_metrics
  files/system_metrics
  files/vmware_metrics
  functions/generate_metrics_server_command.pp
  manifests/pe_metric.pp
  manifests/sar_metric.pp
  manifests/service/ace.pp
  manifests/service/bolt.pp
  manifests/system.pp
  manifests/system/cpu.pp
  manifests/system/memory.pp
  manifests/system/postgres.pp
  manifests/system/processes.pp
  manifests/system/vmware.pp
  spec/classes/puppet_metrics_collector_system_spec.rb
  spec/functions/generate_metrics_server_command_spec.rb
Labels: enhancement

#124 Additional Test Platforms Added
  .github/workflows/pe_latest_testing.yml
  metadata.json
Labels: maintenance

#125 Readme Update and Addition of SLES 12 Test Platform
  .github/workflows/pe_latest_testing.yml
  .github/workflows/pe_lts_testing.yml
  README.md
  metadata.json
Labels: maintenance

#130 (SUP-2499) Remove Harmful Terminology
  README.md
  functions/hosts_with_pe_profile.pp
Labels: maintenance

#139 Remove system warning entirely
  manifests/system.pp
Labels: bug

#137 (SUP-2568) Skip a release if the version has not changed
  .github/workflows/auto_release.yml
Labels: maintenance

#143 (maint) Move testing matrix to files on disk
  .github/workflows/pe_latest_testing.yml
  .github/workflows/pe_lts_testing.yml
  spec/fixtures/matrix/latest.json
  spec/fixtures/matrix/lts.json
Labels: maintenance
